// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-JeReBJuCiDSXXDUHEcj6gtv3odkUlzs',
    appId: '1:41147470302:web:f7cc20073f8991afbe8d4f',
    messagingSenderId: '41147470302',
    projectId: 'flash-95442',
    authDomain: 'flash-95442.firebaseapp.com',
    storageBucket: 'flash-95442.appspot.com',
    measurementId: 'G-HD3ZW3WDEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcVpa0syccMugwwoW9EW67FjwEk-ocRS4',
    appId: '1:41147470302:android:fd91b38c62f26cfebe8d4f',
    messagingSenderId: '41147470302',
    projectId: 'flash-95442',
    storageBucket: 'flash-95442.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLhJZ7-BWKJP-cdmfp2Q_gCfBku3UkhxQ',
    appId: '1:41147470302:ios:fbee70330751e0a8be8d4f',
    messagingSenderId: '41147470302',
    projectId: 'flash-95442',
    storageBucket: 'flash-95442.appspot.com',
    iosBundleId: 'com.example.flash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLhJZ7-BWKJP-cdmfp2Q_gCfBku3UkhxQ',
    appId: '1:41147470302:ios:c8cdd9c344212311be8d4f',
    messagingSenderId: '41147470302',
    projectId: 'flash-95442',
    storageBucket: 'flash-95442.appspot.com',
    iosBundleId: 'com.example.flash.RunnerTests',
  );
}
